version: "3.9"

services:
  smart_health_app:
    build: .
    container_name: smart-health-risk-predictor
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - STREAMLIT_SERVER_ENABLECORS=false
      - STREAMLIT_SERVER_PORT=8501
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
